# Generated by Django 4.2.13 on 2025-11-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampfireClub",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("avatar_url", models.URLField(blank=True)),
                ("game", models.CharField(blank=True, max_length=64)),
                ("visibility", models.CharField(blank=True, max_length=64)),
                ("created_by_community_ambassador", models.BooleanField(default=False)),
                ("badge_grants", models.JSONField(blank=True, default=list)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampfireMember",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("avatar_url", models.URLField(blank=True)),
                ("club_rank", models.IntegerField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampfireEvent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("cover_photo_url", models.URLField(blank=True)),
                ("map_preview_url", models.URLField(blank=True)),
                ("event_time", models.DateTimeField()),
                ("event_end_time", models.DateTimeField(blank=True, null=True)),
                ("rsvp_status", models.CharField(blank=True, max_length=32)),
                ("created_by_community_ambassador", models.BooleanField(default=False)),
                ("discord_interested", models.IntegerField(default=0)),
                ("badge_grants", models.JSONField(blank=True, default=list)),
                ("campfire_live_event_id", models.CharField(blank=True, max_length=64)),
                (
                    "campfire_live_event_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("checked_in_members_count", models.IntegerField(default=0)),
                ("members_total", models.IntegerField(default=0)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.campfireclub",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to="api.campfiremember",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="campfireclub",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clubs_created",
                to="api.campfiremember",
            ),
        ),
        migrations.CreateModel(
            name="CampfireEventRSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="api.campfireevent",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="api.campfiremember",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "member")},
            },
        ),
    ]
