# Generated by Django 4.2.13 on 2025-11-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_campfireclub_campfiremember_campfireevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campfireclub",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campfire_club",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
